export enum Specialite {
    
  SCIENCES_MATH_A = 'SCIENCES_MATH_A',
  SCIENCES_MATH_B = 'SCIENCES_MATH_B',
  SCIENCES_PHYSIQUES = 'SCIENCES_PHYSIQUES',
  SCIENCES_VIE_TERRE = 'SCIENCES_VIE_TERRE',
  SCIENCES_AGRO = 'SCIENCES_AGRO',
  SCIENCES_ECONOMIQUES = 'SCIENCES_ECONOMIQUES',
  GESTION_ACCOUNTING = 'GESTION_ACCOUNTING',
  LETTRES_MODERNES = 'LETTRES_MODERNES',
  LETTRES_CLASSIQUES = 'LETTRES_CLASSIQUES',
  SCIENCES_HUMAINES = 'SCIENCES_HUMAINES',
  ARTS_APPLIQUES = 'ARTS_APPLIQUES'
}
